# Generated by Django 3.2.21 on 2023-09-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo',
            new_name='codigo_curso',
        ),
    ]
