# Generated by Django 3.2.21 on 2023-09-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_faculdade_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculdade',
        ),
    ]
